In [18]:
import os
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords

# Downloading NLTK data
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

pd.set_option("display.max_columns", None)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

In [7]:
RAW_DATASET_PATH = "dataset/raw/emails.csv"

df = pd.read_csv(RAW_DATASET_PATH, encoding='latin1')

df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5728 non-null   str
 1   spam    5728 non-null   int64
dtypes: int64(1), str(1)
memory usage: 89.6 KB

In [13]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(33)

In [15]:
df = df.drop_duplicates(keep = 'first')

In [16]:
df.shape

(5695, 2)

In [19]:
def add_new_features(df):
    df = df.copy()

    df["num_chars"] = df["text"].str.len()
    df["num_words"] = df["text"].apply(lambda x: len(nltk.word_tokenize(x)))
    df["num_sentences"] = df["text"].apply(lambda x: len(nltk.sent_tokenize(x)))

    return df


df = add_new_features(df)

In [22]:
df.head()

,text,spam,num_chars,num_words,num_sentences
0,Subject: naturally irresistible your corporate...,1,1484,325,11
1,Subject: the stock trading gunslinger fanny i...,1,598,90,1
2,Subject: unbelievable new homes made easy im ...,1,448,88,4
3,Subject: 4 color printing special request add...,1,500,99,5
4,"Subject: do not have money , get software cds ...",1,235,53,9

In [24]:
PROCESSED_DATA_PATH = os.path.join(".", "dataset", "processed_data")
os.makedirs(PROCESSED_DATA_PATH, exist_ok=True)
CSV_PATH = os.path.join(PROCESSED_DATA_PATH, "emails_processed.csv")

df.to_csv(CSV_PATH, index=False)